export {CompanyHeader} from "../pages/company/CompanyHeader.tsx";
export {Profile} from "../pages/profile.tsx";
export {SupportHome} from "../pages/suport_home.tsx";
export {SettingsHome} from "./settings/settings_home.tsx";
export {ClosePage} from "../pages/ClosePage.tsx";
export {EnterCompany} from "../pages/company/enter_company.tsx";
export {RegCompany} from "../pages/company/reg_company.tsx";
export {NotFound} from "../pages/NotFound/NotFound.tsx"
export {BodyLogout} from "../pages/Logout.tsx"